# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

[book]
authors = ["novafacing"]
language = "en"
src = "src"
title = "simulator-bindings"

[output.html]

[output.linkcheck2]
